# Build context
- BUILD_BUILDID
- BUILD_BUILDNUMBER
- BUILD_DEFINITIONNAME
- BUILD_REASON
- BUILD_SOURCEBRANCH
- BUILD_SOURCEBRANCHNAME
- BUILD_SOURCEVERSION
- BUILD_SOURCEVERSIONAUTHOR
- BUILD_SOURCEVERSIONMESSAGE
- BUILD_REPOSITORY_NAME
- BUILD_REPOSITORY_PROVIDER

# Paths
- BUILD_SOURCESDIRECTORY
- BUILD_ARTIFACTSTAGINGDIRECTORY
- BUILD_BINARIESDIRECTORY
- AGENT_BUILDDIRECTORY
- AGENT_TEMPDIRECTORY
- AGENT_TOOLSDIRECTORY
- COMMON_TESTRESULTSDIRECTORY
- PIPELINE_WORKSPACE

# System / org
- SYSTEM_COLLECTIONURI
- SYSTEM_TEAMPROJECT
- SYSTEM_JOBDISPLAYNAME
- SYSTEM_PIPELINESTARTTIME

# Agent
- AGENT_NAME
- AGENT_OS
- AGENT_OSARCHITECTURE
- AGENT_VERSION
- ImageOS
- ImageVersion

# Our variables
- RepositoryRoot
- TF_BUILD
